Major updates to allow for parallel building. Turn on PARALLEL=1 in cronjob.weekly and all build types for 1 arch will be run at once.
If you want to run more than that (i.e. multiple arches in parallel
too), then you'll need to tweak slightly more yet. Main issue is the
svn update and popcon update code, then the build lock file. More to
come on that front later...

Rather than rely on the exit status of testingcds, it will now write a
trace file as it exits. This will give us the end time and an error
code that we can parse safely.

Initial testing with 6 arches at once on the new CD build machine
shows that we can build those 6 arches in parallel in well under an
hour. The Squeeze release should be much quicker than Lenny was!

diff --git a/testingcds b/testingcds
--- a/testingcds
+++ b/testingcds
@@ -15,6 +15,10 @@
 CONF=~/build/CONF.sh
 export CF=$CONF
 
+now () {
+    date -u +%F:%H:%M:%S
+}
+
 # Set up and cleaning
 if [ $# -lt 1 ] ; then
     echo $0 \$ARCH
@@ -75,6 +79,12 @@ esac
 
 if [ "$OUT_TYPE"x = ""x ] ; then
     OUT_TYPE=cd
+fi
+
+if [ "$BUILDNAME"x = ""x ] ; then
+    TRACEFILE="$OUT_TYPE-trace"
+else
+    TRACEFILE="$BUILDNAME-trace"
 fi
 
 export IMAGETARGET=official_images
@@ -139,12 +149,12 @@ if ./build.sh "$ARCH" >>"$LOGFILE" 2>&1 ; then
         for i in "$OUT"/*-1.iso; do
             BASE=`basename $i .iso`
             NETINSTNAME=`echo $BASE | sed 's/-BC-1/-businesscard/g;s/-NETINST-1/-netinst/g'`
-            mv $OUT/$BASE.iso $TOPDIR/iso-cd/$NETINSTNAME.iso
+            mv -v $OUT/$BASE.iso $TOPDIR/iso-cd/$NETINSTNAME.iso
             cat $OUT/$BASE.jigdo | \
                 sed 's/-BC-1/-businesscard/g;s/-NETINST-1/-netinst/g' | \
                 gzip --best --no-name > $TOPDIR/jigdo-cd/$NETINSTNAME.jigdo
             rm $OUT/$BASE.jigdo
-            mv $OUT/$BASE.template $TOPDIR/jigdo-cd/$NETINSTNAME.template
+            mv -v $OUT/$BASE.template $TOPDIR/jigdo-cd/$NETINSTNAME.template
         done
         rm -f "$OUT"/*
 
@@ -171,7 +181,8 @@ if ./build.sh "$ARCH" >>"$LOGFILE" 2>&1 ; then
         cat "$OUT"/SHA1SUMS$SUMS_EXTENSION >> "$PUBDIRJIG"/$OUTARCH/iso-${OUT_TYPE}/SHA1SUMS$SUMS_EXTENSION
         mv "$OUT"/*.iso    "$PUBDIRJIG"/$OUTARCH/iso-${OUT_TYPE}
 
-        date > "$PUBDIRJIG"/$OUTARCH/"$OUT_TYPE"-trace
+        DATE=`now`
+        echo -e "end=$DATE\nerror=0\n" > "$PUBDIRJIG"/$OUTARCH/$TRACEFILE
     fi
 
     touch $TDIR/$CODENAME/1.pkgs_extracted # so we don't get errors below
@@ -208,4 +219,8 @@ else
             mail -s "testingcds $RUN has failed; log included" "$i"
     done
     overview "$RUN" failed
+    DATE=`now`
+    mkdir -p "$PUBDIRJIG"/$OUTARCH
+    echo -e "end=$DATE\nerror=1\n" > "$PUBDIRJIG"/$OUTARCH/$TRACEFILE
+    exit 1
 fi
