Sync up current scripts into svn:
 * CD and DVD builds better integrated into cronjob.weekly; removed
   old .cds and .dvds scripts
 * JTE is now merged into mainstream
 * Output layout dirs moved around to match the sarge release images
 * Stopped using the jigdotemplates/ subdir for template files

diff --git a/testingcds b/testingcds
--- a/testingcds
+++ b/testingcds
@@ -36,65 +36,78 @@
 
 
 # Set up and cleaning
-if [ $# -lt 1 ]
-then
-  echo $0 \$ARCH
-  echo "variables: PUBDIR[ISO|JIG]"
-  exit 1
+if [ $# -lt 1 ] ; then
+    echo $0 \$ARCH
+    echo "variables: PUBDIR[ISO|JIG]"
+    exit 1
 fi
 
-if [ ! "$DATE" ];then DATE=`/bin/date -u +%Y%m%d`;fi
+if [ ! "$DATE" ] ; then
+    DATE=`/bin/date -u +%Y%m%d`
+fi
 
 export ARCH=$1
 export PATH=`pwd`/debootstrap/usr/sbin:$PATH:/sbin:/usr/sbin
-if [ ! "$PUBDIRJIG" ];then PUBDIRJIG=/org/cdimage.debian.org/www/testing/cd;fi
-if [ ! "$PUBDIRISO" ];then PUBDIRISO=/org/cdimage.debian.org/www/testing;fi
-if [ ! "$JIGDOFALLBACKURLS" ];then
-   if [ "$ARCH" = "amd64" ];then
-     export JIGDOFALLBACKURLS="Debian=http://amd64-cdsnap.debian.net/cdimage/snapshot-amd64/Debian/"
+
+if [ ! "$PUBDIRJIG" ] ; then
+    PUBDIRJIG=/org/cdimage.debian.org/www/testing/weekly-builds
+fi
+if [ ! "$PUBDIRISO" ] ; then
+    PUBDIRISO=/org/cdimage.debian.org/www/testing/weekly-builds
+fi
+if [ ! "$JIGDOFALLBACKURLS" ] ; then
+   if [ "$ARCH" = "amd64" ] ; then
+       export JIGDOFALLBACKURLS="Debian=http://amd64-cdsnap.debian.net/cdimage/snapshot-amd64/Debian/"
    else
-     export JIGDOFALLBACKURLS="Debian=http://us.cdimage.debian.org/cdimage/snapshot/Debian/"
+       export JIGDOFALLBACKURLS="Debian=http://us.cdimage.debian.org/cdimage/snapshot/Debian/"
    fi
 fi
+
 # $DI is used to set DI_CODENAME and also to specify the directory for images
-if [ "$DI" ];then
-  export DI_CODENAME="$DI"
-  PUBDIRJIG="$PUBDIRJIG"/"$DI"_d-i
-  PUBDIRISO="$PUBDIRISO"/"$DI"_d-i  
+if [ "$DI" ] ; then
+    export DI_CODENAME="$DI"
+    PUBDIRJIG="$PUBDIRJIG"/"$DI"_d-i
+    PUBDIRISO="$PUBDIRISO"/"$DI"_d-i
 fi
 
 CALC="Using previous sizes estimations."
-if [ "$INSTALLER_CD" = "1" -o "$INSTALLER_CD" = "2" ]
-then
-  # Do a tradicional build for the ISOs of the small cds
-  cd debian-cd &&
-    . ../CONF.sh
+if [ "$INSTALLER_CD" = "1" -o "$INSTALLER_CD" = "2" ] ; then
+    # Do a traditional build for the ISOs of the small cds
+    cd debian-cd && \
+        . ../CONF.sh
     # this is for build.sh
     export CF=../CONF.sh
     export IMAGETARGET=bin-official_images
     # to save some time
     export SKIPMIRRORCHECK=yes
 else
-  # Do the size stimation and a JTE build for jigdos
-  cd debian-cd-jte &&
-    . ../CONF.sh &&
-    export IMAGETARGET="ok bootable upgrade bin-infos bin-list" &&
-    export CF=../CONF.sh &&
-    ./build.sh $ARCH >/dev/null 2>&1 &&
-    cd tools && CALC=`./calc` && cd ..
+    # Do the size estimation and a JTE build for jigdos
+    cd debian-cd && \
+        . ../CONF.sh && \
+        export IMAGETARGET="ok bootable upgrade bin-infos bin-list" && \
+        export CF=../CONF.sh && \
+        ./build.sh $ARCH >/dev/null 2>&1 && \
+        cd tools && \
+        CALC=`./calc` && \
+        cd ..
     # this is for build.sh
-    if [ "$ARCH" = "i386" ]
-    then
-      export IMAGETARGET=official_images
+    if [ "$ARCH" = "i386" ] ; then
+        export IMAGETARGET=official_images
     else
-      export IMAGETARGET=bin-official_images
+        export IMAGETARGET=bin-official_images
     fi
 fi
 
-if [ ! "$OUT" ];then echo Error on the config;exit 1;fi
+if [ ! "$OUT" ] ; then
+    echo Error on the config
+    exit 1
+fi
 
-if [ "$INSTALLER_CD" = "1" ];then export OFFICIAL="Official BusinessCard Snapshot";fi
-if [ "$INSTALLER_CD" = "2" ];then export OFFICIAL="Official NetInst Snapshot";fi
+if [ "$INSTALLER_CD" = "1" ] ; then
+    export OFFICIAL="Official BusinessCard Snapshot"
+elif [ "$INSTALLER_CD" = "2" ] ; then
+    export OFFICIAL="Official NetInst Snapshot"
+fi
 
 export LOG="`pwd`/../log/"
 export RUN="$INSTALLER_CD$DI$ARCH"
@@ -121,141 +134,122 @@ DEBOOTUDEB=`/bin/sed -n \
   's/Filename: \(pool\/main\/d\/debootstrap\/debootstrap-udeb.*udeb\)$/\1/p' \
   $MIRROR/dists/sid/main/debian-installer/binary-$ARCH/Packages`
 #  $MIRROR/dists/$DI_CODENAME/main/debian-installer/binary-$ARCH/Packages`
-if [ -z "$DEBOOTUDEB" ];then exit 1;fi
+
+if [ -z "$DEBOOTUDEB" ] ; then
+    exit 1
+fi
+
 echo "$CALC" >"$LOGFILE"
-echo Using ${DEBOOTUDEB##*/} to get packages used by d-i. >>"$LOGFILE"
+echo Using ${DEBOOTUDEB##*/} to get packages used by d-i. >> $LOGFILE
 rm -rf ../debootstrap
 dpkg -x "$MIRROR/$DEBOOTUDEB" ../debootstrap
 
 # Do the actual building
-if ./build.sh $ARCH >>"$LOGFILE" 2>&1;then
+if ./build.sh $ARCH >>"$LOGFILE" 2>&1 ; then
+    # if it went ok get things ready for publishing
+    # we treat the netinst images in a different way
+    if [ "$INSTALLER_CD" = "1" -o "$INSTALLER_CD" = "2" ] ; then
 
-# if it went ok get things ready for publishing
+        ##################################
+        # NETINST STUFF (ISO ONLY for now)
+        ##################################
 
-# we treat the netinst images in a different way
+        # make the dirs we'll use to publish things
+        mkdir -p "$OUT"/$ARCH
 
-if [ "$INSTALLER_CD" = "1" -o "$INSTALLER_CD" = "2" ]
-then
+        # rename the isos from .raw to .iso and put them in their place
+        for i in "$OUT"/*-1.raw
+        do
+            I=${i##*/}
+            if [ "$INSTALLER_CD" = "1" ] ; then
+                NETINSTNAME=${I%-binary-1.raw}-businesscard.iso
+            else
+                NETINSTNAME=${I%-binary-1.raw}-netinst.iso
+            fi
+            mv $i "$OUT"/$ARCH/$NETINSTNAME
+        done
 
-# NETINST STUFF (ISO ONLY)
+        # change images names from raw to iso on the MD5SUMS
+        sed "s/[^ ]*-1.raw$/$NETINSTNAME/" "$OUT"/MD5SUMS >>"$OUT"/$ARCH/MD5SUMS
 
-# make the dirs we'll use to publish things
-  mkdir -p "$OUT"/$ARCH
-# rename the isos from .raw to .iso and put them in their place
-  for i in "$OUT"/*-1.raw
-  do
-    I=${i##*/}
-    if [ "$INSTALLER_CD" = "1" ];then
-      NETINSTNAME=${I%-binary-1.raw}-businesscard.iso
-    else
-      NETINSTNAME=${I%-binary-1.raw}-netinst.iso
+        # Publish the new version
+        mkdir -p "$PUBDIRISO"/$DATE/$ARCH/iso-cd
+        if [ -e "$PUBDIRISO"/$DATE/$ARCH/MD5SUMS/iso-cd ] ; then
+            grep -v $NETINSTNAME "$PUBDIRISO"/$ARCH/$DATE/MD5SUMS/iso-cd > "$PUBDIRISO"/$DATE/$ARCH/iso-cd/MD5SUMS.tmp
+        fi
+        cat "$OUT"/$ARCH/MD5SUMS >> "$PUBDIRISO"/$DATE/$ARCH/iso-cd/MD5SUMS.tmp
+        mv "$PUBDIRISO"/$DATE/$ARCH/iso-cd/MD5SUMS.tmp "$PUBDIRISO"/$DATE/$ARCH/iso-cd/MD5SUMS
+        mv "$OUT"/$ARCH/$NETINSTNAME "$PUBDIRISO"/$DATE/$ARCH/iso-cd
+        rm -f "$PUBDIRISO"/$ARCH/current
+    else 
+        #######################################
+        # NORMAL STUFF - full builds (weekly)
+        #######################################
+        if [ "$INSTALLER_CD"x = "3"x ] ; then
+            OUT_TYPE=dvd
+        else
+            OUT_TYPE=cd
+        fi
+
+        echo Making $ARCH "$OUT_TYPE"s in $OUT "($OUT/$ARCH/jigdo-${OUT_TYPE})"
+
+	    # change images names from raw to iso on the MD5SUMS
+        if [ ! -e $OUT/$ARCH/jigdo-${OUT_TYPE} ] ; then 
+            mkdir -p $OUT/$ARCH/jigdo-${OUT_TYPE}
+        fi
+        sed 's/raw$/iso/' "$OUT"/MD5SUMS >"$OUT"/$ARCH/jigdo-${OUT_TYPE}/MD5SUMS
+
+        # put the templates aside
+        mv "$OUT"/*.template "$OUT"/$ARCH/jigdo-${OUT_TYPE}
+
+        # finish up the jigdos (compress & move them)
+        gzip --best --no-name "$OUT"/*.jigdo
+        for i in "$OUT"/*.jigdo.gz
+        do
+            mv $i ${i%.gz}
+        done
+        mv "$OUT"/*.jigdo "$OUT"/$ARCH/jigdo-${OUT_TYPE}
+
+        # Remove the old version and publish the new one
+        if [ "$IMAGETARGET" = "official_images" ] ; then
+            # Cope with the source discs as well for this arch
+            rm -rf "$PUBDIRJIG"/source/jigdo-${OUT_TYPE}
+            mkdir -p "$PUBDIRJIG"/source/jigdo-${OUT_TYPE}
+            mv "$OUT"/$ARCH/jigdo-${OUT_TYPE}/*-source-*.jigdo "$PUBDIRJIG"/source/jigdo-${OUT_TYPE}
+            grep "source-.*.iso$" "$OUT"/$ARCH/jigdo-${OUT_TYPE}/MD5SUMS > "$PUBDIRJIG"/source/jigdo-${OUT_TYPE}/MD5SUMS
+            mv "$OUT"/$ARCH/jigdo-${OUT_TYPE}/*-source-*.template "$PUBDIRJIG"/source/jigdo-${OUT_TYPE}/
+            grep -v "source-.*.iso$" "$OUT"/$ARCH/jigdo-${OUT_TYPE}/MD5SUMS > "$OUT"/$ARCH/jigdo-${OUT_TYPE}/MD5SUMS.new
+            mv "$OUT"/$ARCH/jigdo-${OUT_TYPE}/MD5SUMS.new "$OUT"/$ARCH/jigdo-${OUT_TYPE}/MD5SUMS
+        fi
+        # Now do the binaries
+        rm -rf "$PUBDIRJIG"/$ARCH/jigdo-${OUT_TYPE}
+        mkdir -p "$PUBDIRJIG"/$ARCH/jigdo-${OUT_TYPE}
+        mv "$OUT"/$ARCH/jigdo-${OUT_TYPE}/* "$PUBDIRJIG"/$ARCH/jigdo-${OUT_TYPE}/
     fi
-    mv $i "$OUT"/$ARCH/$NETINSTNAME
-  done
-# change images names from raw to iso on the MD5SUMS
-  sed "s/[^ ]*-1.raw$/$NETINSTNAME/" "$OUT"/MD5SUMS >>"$OUT"/$ARCH/MD5SUMS
-# Publish the new version
-  mkdir -p "$PUBDIRISO"/$ARCH/$DATE
-  if [ -e "$PUBDIRISO"/$ARCH/$DATE/MD5SUMS ];then
-    grep -v $NETINSTNAME "$PUBDIRISO"/$ARCH/$DATE/MD5SUMS > "$PUBDIRISO"/$ARCH/$DATE/MD5SUMS.tmp
-  fi
-  cat "$OUT"/$ARCH/MD5SUMS >> "$PUBDIRISO"/$ARCH/$DATE/MD5SUMS.tmp
-  mv "$PUBDIRISO"/$ARCH/$DATE/MD5SUMS.tmp "$PUBDIRISO"/$ARCH/$DATE/MD5SUMS
-  mv "$OUT"/$ARCH/$NETINSTNAME "$PUBDIRISO"/$ARCH/$DATE/
-  rm -f "$PUBDIRISO"/$ARCH/current
-  ln -s $DATE "$PUBDIRISO"/$ARCH/current
-# Remove the oldest daily builds, leave only the last 3
-  NUM=`/bin/ls -d "$PUBDIRISO"/$ARCH/20*/|wc -l`
-  NUM=$(($NUM-3))
-  /bin/ls -d "$PUBDIRISO"/$ARCH/20*/|head -n $NUM|tr '\012' '\000'|xargs -0 /bin/rm -rf --
 
-else 
+    # Mail the cd sizes of the cds
+    if [ -e "../.debian-cd.mail" ] ; then
+        MYEMAIL=`grep -v "^#" "../.debian-cd.mail"`
+    else
+        MYEMAIL=`whoami`
+    fi
 
-# NORMAL STUFF, IE NORMAL ISO and JIGDO
+    for i in $MYEMAIL
+    do
+        grep "extents written" "$LOGFILE"|mail -s "testingcds $RUN went ok" "$i"
+    done
+    overview "$RUN" success
 
-# ISO STUFF
-
-if [ "$DOJIGDO" != 2 ]
-then
-# make the dirs we'll use to publish things
-  mkdir -p "$OUT"/isos/$ARCH
-# rename the isos from .raw to .iso and put them in their place
-  for i in "$OUT"/*.raw
-  do
-    I=${i##*/}
-    mv $i "$OUT"/isos/$ARCH/${I%.raw}.iso
-  done
-# change images names from raw to iso on the MD5SUMS
-  sed 's/raw$/iso/' "$OUT"/MD5SUMS >"$OUT"/isos/$ARCH/MD5SUMS
-# Remove the old version and publish the new one
-  rm -rf "$PUBDIRISO"/isos/$ARCH/
-  mkdir -p "$PUBDIRISO"/isos/
-  mv "$OUT"/isos/$ARCH/ "$PUBDIRISO"/isos/$ARCH/
-fi
-
-# JIGDO STUFF
-
-if [ "$DOJIGDO" != 0 ]
-then
-# make the dirs we'll use to publish things
-  mkdir -p "$OUT"/jigdo-area/$ARCH/jigdotemplates
-# change images names from raw to iso on the MD5SUMS
-  sed 's/raw$/iso/' "$OUT"/MD5SUMS >"$OUT"/jigdo-area/$ARCH/MD5SUMS
-# put the templates aside
-  mv "$OUT"/*.template "$OUT"/jigdo-area/$ARCH/jigdotemplates
-# finish up the jigdos (compress & move them)
-  gzip --best --no-name "$OUT"/*.jigdo
-  for i in "$OUT"/*.jigdo.gz;do mv $i ${i%.gz};done
-  mv "$OUT"/*.jigdo "$OUT"/jigdo-area/$ARCH/
-# Remove the old version and publish the new one
-  if [ "$IMAGETARGET" = "official_images" ]
-  then
-    rm -rf "$PUBDIRJIG"/jigdo-area/source/
-    mkdir -p "$PUBDIRJIG"/jigdo-area/source/jigdotemplates/
-    mv "$OUT"/jigdo-area/$ARCH/*-source-*.jigdo "$PUBDIRJIG"/jigdo-area/source/
-    grep "source-.*.iso$" "$OUT"/jigdo-area/$ARCH/MD5SUMS > "$PUBDIRJIG"/jigdo-area/source/MD5SUMS
-    mv "$OUT"/jigdo-area/$ARCH/jigdotemplates/*-source-*.template "$PUBDIRJIG"/jigdo-area/source/jigdotemplates/
-    grep -v "source-.*.iso$" "$OUT"/jigdo-area/$ARCH/MD5SUMS > "$OUT"/jigdo-area/$ARCH/MD5SUMS.new
-    mv "$OUT"/jigdo-area/$ARCH/MD5SUMS.new "$OUT"/jigdo-area/$ARCH/MD5SUMS
-  fi
-  rm -rf "$PUBDIRJIG"/jigdo-area/$ARCH/
-  mkdir -p "$PUBDIRJIG"/jigdo-area/
-  mv "$OUT"/jigdo-area/$ARCH/ "$PUBDIRJIG"/jigdo-area/$ARCH/
-# Calculate snapshot path, remove the old snapshot and publish the new one
-#  SNAP=${JIGDOFALLBACKURLS##Debian=http://us.cdimage.debian.org/cdimage/}
-#  SNAP=${PUBDIRJIG%%testing*}${SNAP%%/Debian*}
-#  mkdir -p "$SNAP"
-#  mv "$OUT"/snapshot/* "$SNAP"
-# Remove the oldest snapshots, leave only the last 2
-#  NUM=`/bin/ls -d "${SNAP%%/$DATE}"/20*/|wc -l`
-#  NUM=$(($NUM-2))
-#  /bin/ls -d "${SNAP%%/$DATE}"/20*/|head -n $NUM|tr '\012' '\000'|xargs -0 /bin/rm -rf --
-fi
-
-fi
-
-# Mail the cd sizes of the cds
-if [ -e "../.debian-cd.mail" ]
-then
-  MYEMAIL=`grep -v "^#" "../.debian-cd.mail"`
 else
-  MYEMAIL=`whoami`
-fi
-  for i in $MYEMAIL
-  do
-    grep "extents written" "$LOGFILE"|mail -s "testingcds $RUN went ok" "$i"
-  done
-  overview "$RUN" success
-else
-if [ -e "../.debian-cd.mail" ]
-then
-  MYEMAIL=`grep -v "^#" "../.debian-cd.mail"`
-else
-  MYEMAIL=`whoami`
-fi
-  for i in $MYEMAIL
-  do
-    echo Error when trying to create cds for $RUN|mail -s "testingcds $RUN has failed" "$i"
-  done
-  overview "$RUN" failed
+    # Run failed
+    if [ -e "../.debian-cd.mail" ] ; then
+        MYEMAIL=`grep -v "^#" "../.debian-cd.mail"`
+    else
+        MYEMAIL=`whoami`
+    fi
+    for i in $MYEMAIL
+    do
+        echo Error when trying to create cds for $RUN|mail -s "testingcds $RUN has failed" "$i"
+    done
+    overview "$RUN" failed
 fi
